/* delayed-load.h generated by valac 0.18.0, the Vala compiler, do not modify */


#ifndef __DEFAULT_EXTENSIONS_DELAYED_LOAD_H__
#define __DEFAULT_EXTENSIONS_DELAYED_LOAD_H__

#include <glib.h>

G_BEGIN_DECLS



MidoriExtension* extension_init (void);


G_END_DECLS

#endif
